### ISSUE TITLE
Stream theories

### ISSUE THREAD

**Issue by canmingir** [centaur-ai/PWL#1]
- Current PWL can take UUID as `--id` argument 
- All theories should append file with UUID name in JSONL format.
`401d68be-33aa-46b2-99db-c75e062a9ca9.jsonl`
- As MCMC generates a theory, it is added to the file
`{ "theory": "..." }`
- Streaming is in `/tmp` folder with `centaur` folder and given id 
- If id argument is not provided, streaming is skipped

**Comment by canmingir** [comment]
@StphnWright I am going to need a flag that indicates of starting and ending of stream, so I think it is better to add type in the JSON.

```
{ "type": "system", "event": "stream_start" }
{ "type": "theory", ... }
{ "type": "system", "event": "stream_end" }
```

What do you think something like that 👆?

**Comment by canmingir** [comment]
Let's also use `utf-8` for encoding

**Comment by StphnWright** [comment]
Pushed updated pwl_reasoner.cpp. 

In this update to pwl_reasoner, we're moving from manually creating JSON streams to having them automatically generated during the reasoning process with the specified requirements:

1. UUID Integration:
- All theories should append the file with UUID to create/identify stream files
- Makes each reasoning session uniquely identifiable

2. File Structure:
- Uses JSONL format (one JSON object per line)
- Stored in temporary directory structure
- Named after the session UUID

3. Dynamic Generation:
- As MCMC runs and generates theories, it automatically appends to the JSONL file
- Each theory state outputs in the following format:

```json
{"type":"axiom","axiom":"∀x₁((man(x₁) → mortal(x₁)))","description":"Added logical form to theory","rate":"-75.570909","created_at":"2024-12-26T18:32:00Z"}
{"type":"axiom","axiom":"∀x₁((man(x₁) → mortal(x₁)))","description":"Best theory after optimization","rate":"-75.529207","created_at":"2024-12-26T18:32:00Z"}
{"type":"axiom","axiom":"∃x₁(∃x₂(name(x₂) ∧ arg1(x₂)=x₁ ∧ arg2(x₂)="Socrates") ∧ man(x₁))","description":"Added logical form to theory","rate":"-2233.730509","created_at":"2024-12-26T18:32:00Z"}
{"type":"axiom","axiom":"∃x₁(∃x₂(name(x₂) ∧ arg1(x₂)=x₁ ∧ arg2(x₂)="Socrates") ∧ man(x₁))","description":"Best theory after optimization","rate":"-2233.648105","created_at":"2024-12-26T18:32:00Z"}
{"type":"query","axiom":"∃x₁(∃x₂(name(x₂) ∧ arg1(x₂)=x₁ ∧ arg2(x₂)="Socrates") ∧ mortal(x₁))","description":"Query result","rate":"1.000000","created_at":"2024-12-26T18:32:00Z"}
```

4. Optional Streaming:
- Only generates streams if --id is provided
- Otherwise, runs normally without stream generation
